import BreadCrumbs from "@/components/BreadCrumbs";
import Contact from "@/components/Contact";
import Faq from "@/components/Faq";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import Project from "@/components/Projects";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="Pages" className="bg-zircon" />
      <BreadCrumbs links={[{name: "Home", href: "/"}, {name: "Our Projects"}]} />
      <Project />
      {children}
      <Faq />
      <Contact />
      <Footer />
    </>
  );
}
