import ContactForm from "@/components/ContactForm";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Faq",
  description: "Generated by create next app",
};

export default function FaqLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="Faq" className="bg-zircon" />
      {children}
      <ContactForm />
      <Footer />
    </>
  );
}
