import Contact from "@/components/Contact";
import Faq from "@/components/Faq";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Detail Service",
  description: "Generated by create next app",
};

export default function DetailServiceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="Service" className="bg-zircon" />
      {children}
      <Faq />
      <Contact />
      <Footer />
    </>
  );
}
