import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import Team from "@/components/Team";
import Testimonials from "@/components/Testimonials";
import Works from "@/components/Works";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="About" className="bg-zircon" />
      {children}
      <Team />
      <Works />
      <Testimonials />
      <Contact />
      <Footer />
    </>
  );
}
