import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Contact us",
  description: "Generated by create next app",
};

export default function ContactLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="Contact" className="bg-zircon" />
      {children}
      <Footer />
    </>
  );
}
