import BreadCrumbs from "@/components/BreadCrumbs";
import Contact from "@/components/Contact";
import Faq from "@/components/Faq";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import Testimonials from "@/components/Testimonials";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Testimonial",
  description: "Generated by create next app",
};

export default function TestimonialLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="Testimonial" className="bg-zircon" />
      <BreadCrumbs links={[{name: "Home", href: "/"}, {name: "Testimonial"}]} />
      <Testimonials />
      {children}
      <Faq />
      <Contact />
      <Footer />
    </>
  );
}
