import type { Metadata } from "next";
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from "@mantine/core";
import { theme } from "@/theme";
// styles
import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import '@mantine/dropzone/styles.css';
import '@mantine/notifications/styles.css';
import "./globals.css";
import { GlobalContextProvider } from "@/context/store";
import { Notifications } from '@mantine/notifications';
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Creative agency site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Notifications />
          <GlobalContextProvider>
            <Suspense fallback={<div>Loading ...</div>}>{children}</Suspense>
          </GlobalContextProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
