import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Terms of Conditions",
  description: "Generated by create next app",
};

export default function TermsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="Terms" className="bg-zircon" />
      {children}
      <Footer />
    </>
  );
}
