import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Our team",
  description: "Generated by create next app",
};

export default function TeamLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav activeMenuName="Team" className="bg-zircon" />
      {children}
      <Contact />
      <Footer />
    </>
  );
}
