import Project from "@/components/Projects";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Project",
  description: "Generated by create next app",
};

export default function ProjectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <Project />
    </>
  );
}
